gymnastjs/gymnast

- .babelrc
- circle.yml
- package.json
- test/Storyshots.spec.js
- test/__mocks__/styleMock.js
- test/__snapshots__/Storyshots.spec.js.snap
- yarn.lock
Closes https://github.com/obartra/flexgrid/issues/3
> feat(test): Add snapshots 📸

- .babelrc
- package.json
- src/grid.hoc.js
- src/grid.js
- src/item.hoc.js
- src/utils.js
- stories/box.js
- stories/layout/autoflow.js
- stories/layout/fraction.js
- stories/layout/nested.js
- stories/layout/offset.js
- stories/layout/sizing.js
- storybook/config.js
- test/__snapshots__/Storyshots.spec.js.snap
- yarn.lock
Add react storybook info addon
Add descriptions of behavior on each section
> feat(storybook): Add info addon

- README.md
- package.json
- scripts/formatcss.sh
- yarn.lock
Add commitizen with conventional changelog
> feat(build): Add commitizen

- package.json
- src/flex.css
- src/grid.hoc.js
- src/item.hoc.js
- src/utils.js
- src/values.js
- stories/box.js
- stories/grid/align.js
- stories/grid/autoflow.js
- stories/grid/fraction.js
- stories/grid/nested.js
- stories/grid/offset.js
- stories/grid/sizing.js
- stories/index.js
- test/__snapshots__/Storyshots.spec.js.snap
Add examples
Cleanup css
Closes https://github.com/obartra/flexgrid/issues/22
> refactor(grid): Cleanup css

- postcss.config.js
- src/flex.css
- src/grid.hoc.js
- src/item.hoc.js
- src/item.js
- stories/grid/align.js
- `max-width` did not respect the max rendered content width. Updated to reflect that
- Cleanup css
Closes #26
> fix(grid): Correct max-width

- README.md
greenkeeper is simple to use but I've no idea what they did with greenkeeper-lockfile. Removing until
they provide better instructions
Closes #25
> feat(greenkeeper): Remove

- .eslintrc
- yarn.lock
Enable no-deprectated rules for React 15.5 onwards
Closes https://github.com/obartra/flexgrid/issues/39
> feat(lint): Enable no-deprecated rules

- circle.yml
- scripts/deploystorybook.sh
- stories/layout/holyGrail.js
- test/__snapshots__/Storyshots.spec.js.snap
WIP, move scripts outside circle.yml (and only run when `CI` is set)
- Deploy master to `/` (current behavior)
- Deploy development branches to `/branch/branchname`.
- These are not meant to be dependeable links since they will be overwritten on redploy
Closes https://github.com/obartra/flexgrid/issues/38
> feat(deploy): Deploy PRs

- package.json
- scripts/deploystorybook.sh
- test/__mocks__/styleMock.js
- yarn.lock
Force removing any untracked files from gh-pages
Update dependencies
Closes https://github.com/obartra/flexgrid/issues/51
> fix(gh-pages): Update deps and cleanup gh-pages build

- .all-contributorsrc
- .vscode/cSpell.json
- README.md
- package.json
- scripts/deploystorybook.sh
Closes https://github.com/obartra/reflex/issues/61 and https://github.com/obartra/reflex/pull/62
> Add Gitter badge

- package.json
- screener.config.js
- yarn.lock
Add image comparison testing with screener.io
> feat(testing): Add image comparison testing

- package.json
- stories/components/story.js
- stories/configStories.js
- stories/grid/story.js
- stories/layout/story.js
- stories/withExtensions.js
- storybook/addons.js
- storybook/config.js
- yarn.lock
- add forked storybook-jsx-addon with better defaultProps support
- add static property to HOCs to allow for accessing wrapped component display name directly
> feat(docs): add usage documentation

- .gitignore
- screener.config.js
- scripts/deploystorybook.sh
Ensure fonts are loaded on the delpoyed instance as well
> fix(deploy): Load fonts

- src/grid.css
- src/layout.css
- src/layout.hoc.js
- src/utils.js
- stories/layout/cards.js
- stories/layout/layout.css
- storybook/config.js
- test/__snapshots__/Storyshots.spec.js.snap
Add new page layout example
Allow layout to set marginSize (defaults to none, but always hard coded to vertical)
> feat(layout): Add card layout page example

- src/grid.css
- src/grid.hoc.js
- stories/components/header.js
- stories/core/box.js
- stories/core/index.js
- stories/core/position.js
- stories/core/stories.css
- stories/grid/nested.js
- test/__snapshots__/Storyshots.spec.js.snap
WIP, will eventually close https://github.com/obartra/reflex/issues/31
- Improve nesting and header examples to better demonstrate nesting behavior
> refactor(nesting): Expand example

- package.json
- yarn.lock
Updating npm dependencies to latest
> chore(build): Update npm dependencies

- src/grid.css
- src/item.css
- src/item.hoc.js
- src/padding.css
- stories/components/cards.base.js
- stories/components/cards.composite.js
- stories/components/cards.filter.js
- stories/components/cards.profile.js
- stories/core/stories.css
- stories/layout/layout.css
- storybook/config.js
- test/__snapshots__/Storyshots.spec.js.snap
Code available here: https://obartra.github.io/reflex/branch/add-cards
> feature(components): Add card examples

- README.md
- package.json
Closes https://github.com/obartra/reflex/issues/9
> refactor(npm): Rename package

- .vscode/cSpell.json
- CONTRIBUTING.md
- README.md
Add link to wiki usage page (WIP) and to the contributing doc (borrowed from the contributor
covenant)
> docs(README): Add contribution and usage links

- src/layout.css
There were some classes remaining from the last margin / padding refactor.
These changes Remove them
Closes https://github.com/obartra/reflex/issues/128
> refactor(layout): Remove unused css

- package.json
- scripts/webpack.config.js
- src/dev.css
- src/grid.hoc.js
- src/layout.hoc.js
- src/types.js
- src/variables.css
- storybook/shared/box.js
- storybook/shared/variables.css
- storybook/shared/withExtensions.js
- storybook/stories/api/nested.js
- storybook/stories/api/padding.js
- storybook/stories/components/card/base.js
- storybook/stories/components/card/composite.js
- storybook/stories/components/card/filter.js
- storybook/stories/components/card/profile.js
- storybook/stories/components/header/app.js
- storybook/stories/components/search/filters.js
- storybook/stories/components/search/nav.js
- storybook/stories/components/search/results.js
- storybook/stories/examples/cards.js
- storybook/stories/examples/holyGrail.js
- storybook/stories/examples/layout.css
- storybook/stories/examples/report.css
- storybook/stories/examples/report.js
- storybook/stories/examples/search.js
- storybook/stories/examples/twoSections.js
- test/__snapshots__/Storyshots.spec.js.snap
Provides useful debugging tool that clearly shows the boundary of Cols and Grids. Usage is
demonstrated with Storybook Dev Mode toggle.
> feat(dev-mode): adds devMode flag to Layout for enabling colored Grid backgrounds

- storybook/stories/components/search/results.js
`yarn test` was showing some unnecessary warnings. Fixes related issues (by adding keys)
> test(warnings): Reduce warnings when running tests

- CONTRIBUTING.md
- README.md
- package.json
- scripts/citests.sh
- scripts/deploystorybook.sh
- scripts/webpack.config.js
- storybook/config/config.js
- storybook/config/webpack.config.js
- yarn.lock
Add build size check to prevent the gzipped file size of the bundle to grow over 9kb
> ci(build): Measure build size

- package.json
- scripts/webpack.config.js
Added a second, unminified bundle -- useful for debugging -- in addition to the already existing
minified bundle
> build(bundle): update build to generate unminifed and minified bundle

- package.json
- yarn.lock
> deps(yarn): update babel plugin

- README.md
- package.json
- scripts/webpack.config.js
- yarn.lock
BREAKING CHANGE requiredcss moved into separate file
> build(css): extract css into standalone bundle

- storybook/stories/grid/align.md
- storybook/stories/grid/fraction.md
- storybook/stories/grid/justify.md
Update Grid docs for alignment and fraction. They were a bit updated
these changes reflect the current implementation
> docs(storybook): Update grid descriptions

- package.json
- src/base.css
- src/derived/col.js
- src/derived/col.spec.js
- src/grid.js
- src/layout.css
- src/utils.js
- src/utils.spec.js
- storybook/stories/components/pagination.js
- test/__snapshots__/Storyshots.spec.js.snap
- test/screenshot/nightwatch.conf.js
- yarn.lock
margin prop was not allowed in Col because we were setting margin direction
properties and both cannot be set at the same time.
- Not set margin defaults when `margin` prop is passed
- Replace thrown errors with `console.error` to prevent the page from breaking
> feat(col): Allow margin prop

- test/screenshot/commands/sauceEnd.js
- test/screenshot/nightwatch.conf.js
- test/screenshot/shared/index.js
Fix status badge for master builds
Closes https://github.com/obartra/reflex/issues/208
> build(ci): Fix status badge

- src/derived/root.css
- src/derived/root.js
- src/variables.css
- test/__snapshots__/Storyshots.spec.js.snap
- Change page margins to 8px on small screens (less than 600px)
- This requires disabling overflow-x on layout
> feat(layout): Small margins on small screens

- package.json
- scripts/flowsource.sh
Fix flow types exports
Closes https://github.com/obartra/reflex/issues/239
> fix(flow): Fix flow type export

- scripts/deploynpm.sh
This is the third attempt, it's tricky because this script only runs on CI master
> fix(flow): Correct exported flow types

- README.md
Update demo to account for latest version of reflex changes
Closes https://github.com/obartra/reflex/issues/257
> docs(README): Update demo

- renovate.json
Prevent Renovate from creating a million PRs
> ci(renovate): Group dependencies

- README.md
- Remove `dev` parameter
- Remove `Layout` references (switch for wiki link)
> fix(docs): Correct usage documentation

- .babelrc
- test/__snapshots__/storyshots.spec.js.snap
Reduces the bundle size by ~1.3kb
> build(npm): Remove proptypes from the production build

- README.md
- Move documentation to readme.io
> docs(wiki): Replace wiki with readme.io

- src/grid.js
- src/layout.js
Was causing some errors with flow in my project, adding the import to resolve it
> Added an import of React to two files that were missing it

- src/utils/index.js
- src/utils/utils.spec.js
- Add `verticalGutter/2` alias for consistency
> feat(alias): Add support for half vertical alias

- README.md
Update README example
BREAKING CHANGE: version 17.0.1 accidentally included all breaking changes, forcing major release
> fix(publish): publish major version
