gymnastjs/gymnast

flex.css
src/grid.hoc.js
src/item.hoc.js
stories/layout/fraction.js
stories/layout/sizing.js

- max-width did not take margins into account which resulted in incorrect overflow
- grid did not have column sizing which resulted in incorrect sizes for nested grids
Closes https://github.com/obartra/flexgrid/issues/4

fix(grid): Correct grid sizing

---

src/grid.hoc.js
src/item.hoc.js
src/utils.js

Restrict number values to their valid ranges. This approach better leverages React PropType
validation to ensure correct input
Closes #24

feat(errors): Restrict PropTypes

---

.eslintrc
.flowconfig
package.json
src/grid.hoc.js
src/item.hoc.js
src/utils.js
stories/box.js
stories/components/header.js
stories/components/pagination.js
stories/grid/align.js
stories/grid/autoflow.js
stories/grid/fraction.js
stories/grid/nested.js
stories/grid/offset.js
stories/grid/sizing.js
stories/utils.js
yarn.lock

We don't necessarily need to merge this. I mostly was trying this out as an experiment in how flow would integrate into the existing workflow.
It ends up being pretty nice in my opinion.
- More terse, and readable prop type definitions and doesn't rely on external package
- Better intellisense including knowledge of whats being imported from other modules
- Superb type inference even before you explicitly provide types
- Inline/"compile time" errors for invalid types via VS Code plugin and doesn't rely on runtime like prop-types
- Fully opt-in via `// @flow` so if for some reason providing types for a file doesn't make sense, it's simple to turn off type checks
- Even in a smaller project such as this, it managed to catch a potential …

refactor(flow): add type checking via flow

---

package.json
src/grid.css
src/grid.hoc.js
src/item.hoc.js
src/layout.hoc.js
src/utils.js
stories/box.js
stories/layout/holyGrail.js
stories/stories.css
storybook/config.js
storybook/webpack.config.js
test/__snapshots__/Storyshots.spec.js.snap
yarn.lock

- flex.css and storybook styles now use css-modules.
- Update jest module mapper to use identity-obj-proxy for mocking css-module classNames.
Replaces https://github.com/obartra/flexgrid/pull/37

refactor(css): update css to use css-modules

---

src/layout.css
stories/layout/holyGrail.css
stories/stories.css
storybook/config.js

layout and holyGrail were incorrectly relying on the original pure css cascade of class names. This
fixes that and uses additional (cool!) features of css-modules

fix(css): update layout and holyGrail css to css-modules

---

.stylelintrc
src/grid.css
src/layout.css
src/variables.css
stories/components/header.js
stories/components/pagination.js
stories/designGrid.css
stories/grid/alignHorizontal.js
stories/grid/alignVertical.js
stories/grid/autoflow.js
stories/grid/fraction.js
stories/grid/nested.js
stories/grid/offset.js
stories/grid/sizing.js
stories/layout/holyGrail.js
stories/layout/stack.js
stories/layout/twoSections.js
stories/withExtensions.js
test/__snapshots__/Storyshots.spec.js.snap

- Add grid overlay option to all designs
- This highlights issues with some of the examples, issues will be addressed
in subsequent PRs
Rendering looks like this:
Issues examples:

feat(grid): Add grid overlay

---

stories/box.js
stories/components/header.js
stories/components/pagination.js
stories/designGrid.css
stories/layout/stack.js
stories/layout/twoSections.js
test/__snapshots__/Storyshots.spec.js.snap
yarn.lock

Fixes components not aligning to the top level grid (where appropriate)
Layout cases still need to be fixed (as part of https://github.com/obartra/reflex/issues/56 and https://github.com/obartra/reflex/issues/40)
Closes https://github.com/obartra/reflex/issues/60

fix(grid): Align components to the grid

---

package.json
yarn.lock

forked dependencies are no longer required since the main packages have updated their versions with the changes in the forks we were using

chore(deps): replace forked dependencies with updated packages

---

src/grid.css
src/layout.css
src/layout.hoc.js
src/values.js
stories/components/header.js
stories/core/root.js
stories/grid/autoflow.js
stories/layout/holyGrail.js
stories/layout/layout.css
stories/layout/stack.js
stories/layout/twoSections.js
test/__snapshots__/Storyshots.spec.js.snap

These changes simplify the layout to 3 types:
- PARENT: Contains stretch or auto elements, expands to 100% of the container
- STRETCH: Grows to fit, vertical overflow if needed
- AUTO: Size defined by the content, doesn't grow or shrink
To lock a layout element to the top or the bottom of the window you can use: `fixed={Layout.FIXED_POSITION.TOP}` or `fixed={Layout.FIXED_POSITION.TOP}`. This is used by sticky headers while preserving the page scroll.
To change the default overflow setting (overflow: auto) you can set `overflow={Layout.OVERFLOW.NONE}`
Closes https://github.com/obartra/reflex/issues/56

fix(layout): Update layout system

---

LICENSE

Add license (it was already listed as MIT licensed in package.json)

feat(license): Add MIT License text

---

package.json
src/grid.hoc.js
src/item.hoc.js
src/layout.hoc.js
src/utils.js
stories/components/header.js
stories/core/box.js
stories/core/storyFolders.js
stories/grid/autoflow.js
stories/grid/fraction.js
stories/grid/nested.js
stories/grid/sizing.js
stories/grid/verticalAlign.js
stories/layout/stack.js
yarn.lock

Replace custom built utils functions for equivalent lodash methods.
These changes will require some extra setup work when generating the build to ensure
only the methods used are included in the bundle
Closes https://github.com/obartra/reflex/issues/69

refactor(dependencies): Use lodash

---

scripts/deploystorybook.sh

The `rm` command was failing when cleaning up folders, just make it remove everything for simplicity (except for the `branch` folder)
Closes https://github.com/obartra/reflex/issues/83

fix(build): Prevent error on folder cleanup on pre deploy

---

src/grid.css
src/index.css
src/item.css
src/item.hoc.js
stories/components/header.js
stories/core/margin.js
stories/core/stories.css
stories/grid/margin.js
test/__snapshots__/Storyshots.spec.js.snap

- Add `margin` and `marginSize` to item.
If grid margin options are set for all items, the ones on the individual item take precendence.
This allows things like removing all margins except for one item. Added a 'Margin' story that
shows the behavior:
Closes https://github.com/obartra/reflex/issues/55

feat(item): Add individual item margins

---

circle.yml
scripts/citests.sh

Split testing into 2 nodes to increase performance. Currently the biggest bottleneck is the image
comparison tests. This will allow running them while checking linting and unit tests. It should
speed things up by ~1 minute
Closes https://github.com/obartra/reflex/issues/95

ci(performance): Run tests in parallel

---

stories/core/variables.css

Top level iframe font was deployed correctly but not the one within iframes.
By setting them to the same font file path we prevent downloading them twice
(inside and outside the iframe)

fix(fonts): Correct deployed font load

---

.eslintrc
package.json
src/grid.css
src/grid.hoc.js
src/layout.css
src/layout.hoc.js
src/padding.css
src/padding.js
src/types.js
src/utils.js
src/utils.spec.js
stories/core/stories.css
stories/grid/autoflow.js
stories/grid/margin.md
stories/grid/padding.js
stories/grid/padding.md
stories/grid/verticalAlign.md
stories/layout/cards.js
stories/layout/holyGrail.js
stories/layout/report.css
stories/layout/report.js
stories/layout/report.md
stories/layout/stack.js
stories/layout/twoSections.js
storybook/config.js
storybook/manager-head.html
test/__snapshots__/Storyshots.spec.js.snap

- Add padding option to all grids
- Add padding examples
- Add report example
TODO
- Update margin options to use `getSides` for all components
- Polish report example
- Sticky navigation (https://github.com/obartra/reflex/issues/103)
- Tabs should not adhere to the grid but to have an option to size to the min size of the content (https://github.com/obartra/reflex/issues/104)
- Option to increase the separation between items while respecting page margins
Live version available here: https://obartra.github.io/reflex/branch/report (https://github.com/obartra/reflex/issues/105)

feat(layout): Add report layout

---

scripts/deploynpm.sh

Because we publish to gh-pages before deploying to npm, we need to re-run
yarn since we deleted all files in the branch.

fix(deploy): Install before deploy

---

README.md
package.json

Using `xn-reflex` since that one is not taken

refactor(npm): Rename package

---

src/grid.hoc.js
src/padding.js
stories/grid/padding.js
test/__snapshots__/Storyshots.spec.js.snap

Fix bug where align / justify where not applied when padding was used on Grid
Updated padding example available [here](https://obartra.github.io/reflex/branch/fix-padding/?knob-Overlay=false&knob-Items=5&knob-Stretch=true&knob-Margin=Default&knob-Margin%20Size=Default&knob-Items%20Margin=Default&knob-Items%20Margin%20Size=Default&selectedKind=Grid&selectedStory=Padding&full=0&down=1&left=1&panelRight=0&downPanel=storybooks%2Fstorybook-addon-knobs)
Closes https://github.com/obartra/reflex/issues/117

fix(padding): Support align / justify

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md

- Most tooling expects `CODE_OF_CONDUCT.md` file for code of conduct
- Move it from contributing to its own file

docs(conduct): Move code of conduct

---

src/grid.css
src/types.js
stories/core/box.js
stories/core/position.js
stories/grid/padding.js
stories/grid/verticalAlign.js
stories/grid/verticalAlign.md
test/__snapshots__/Storyshots.spec.js.snap

Replace vertical alignmnet (`align` property) "middle" value with "center" so
valid values are now "top", "center", "bottom", "stretch" and `undefined`
BREAKING CHANGE, Closes https://github.com/obartra/reflex/issues/129

refactor(align): Replace 'middle' with 'center'

---

scripts/deploystorybook.sh

CI would fail to deploy to gh-pages because both containers were trying to update them at the same
time. This script encofrces deploy storybook to only occur on node 0

ci(deploy): Fix deploy errors

---

package.json

Was missing a `files` entry in package.json which denotes which files should be published to npm
new files available on npm

fix(publish): include dist files for npm publish

---

README.md
storybook/shared/designGrid.css

- Fix a bug where column width wasn't computed correctly
- Chrome re-renders the gradient background less often than the actual content
which results in inconsistencies when the page is smaller than the max content
size (1224px), after that the content doesn't vary (it's just centered) so
Chrome renders the right background grid.
- To show the design grid but discourage usage, when the window width is less than
1224px, the grid is shown in yellow (which makes it harder to view the edges)
- The Chrome issue can be seen by slowly resizing the window width. At specific pixel sizes it works as expected but then falls behind until the next change (~10px intervals)
Closes https://github.com/obartra/reflex/issues/100

fix(dev): Improve overlay grid

---

storybook/shared/storyFolders.js

Footer notes were only added when an existing md file was present.
Changing the logic because we always want the link to the file, regardless of
whether additional information is available or not.
Closes https://github.com/obartra/reflex/issues/165

fix(notes): Ensure link in notes is always added

---

package.json

This is only relevant if consuming the unminfied source, version.js was not included
as part of the published bunled. Adding to package.json

fix(package): Ensure version.js is published

---

README.md

[This is how it's rendered](https://github.com/obartra/reflex/blob/be939b7e7932d9f4badc1ad7ee6e70fcf8ffdd7b/README.md)
Update readme to better reflect what Reflex does and how to get started
Most of the changes are shamelessly (and heavily) inspired on [React readme](https://github.com/facebook/react/blob/master/README.md)

docs(readme): Better explain reflex usage

---

src/layout.js
src/types.js
storybook/stories/api/autoflow.js
storybook/stories/api/margin.js
storybook/stories/api/verticalAlign.js
storybook/stories/components/card/filter.js
storybook/stories/components/card/profile.js
storybook/stories/components/header/basic.js
storybook/stories/components/search/results.js
storybook/stories/examples/cards.js
storybook/stories/examples/report.js
test/__snapshots__/Storyshots.spec.js.snap

The babel plugin that converts flow types to prop-types was correctly throwing an error.
However, due to a bug in that babel plugin, information about the invalid prop-types were
being obscured.
There is a PR open for this babel plugin that should correct this issue: https://github.com/brigand/babel-plugin-flow-react-proptypes/pull/116

fix(stories): update invalid stories

---

package.json
scripts/postcss.config.js
scripts/replaceEval.js
scripts/webpack.config.js
yarn.lock

- Webpack 2 includes a CSP check which causes an (intended) console error.
- To prevent that (and assume CSP is always enabled) these changes follow
the same pattern than redux and replace it from the build
- Remove comments from the css minified bundle
- Use a single helper definition for babel instead of including it per file
Closes https://github.com/obartra/reflex/issues/175

build(csp): Remove eval from bundle

---

.babelrc
.flowconfig
flow-typed/cssModules.js
package.json
scripts/webpack.config.js
src/reflex.js
storybook/index.js
storybook/stories/components/search/results.js
yarn.lock

- adds build step to copy src files and output to dist as `*.flow`. These files will be picked up by `flow` when type checking
- fixed an issue with flow config where flow was looking at dist for `reflex` components. Although, this could theoretically be resolved by the new build step implemented here.
Resolves https://github.com/obartra/reflex/issues/144

feat(flow): add flow types to dist

---

scripts/deploynpm.sh

I missed the fact that CI runs scripts from the root of the project rather than the relative path between shell script and node script.

fix(build): target correct file path for CSS flow

---

src/base.js
src/derived/col.js
src/derived/grid8.js
src/layout.js
src/reflex.js
src/utils.js
src/utils.spec.js
storybook/stories/components/search/filters.js

With base now it's easy to create additional grids with different bases.
Grid8 would allow us to implement things like small cards without either having
to directly set css or use imprecise fractions

feat(grid8): Update Base to take a base unit

---

package.json
src/base.css
src/layout.css
storybook/shared/designGrid.css
storybook/shared/withExtensions.js
storybook/stories/examples/report.js
storybook/stories/examples/search.js
storybook/stories/examples/twoSections.js
storybook/stories/layout/stack.js
test/__snapshots__/Storyshots.spec.js.snap
test/screenshot/specs/index.js

- Add support for IE11
- To ensure consistent cross-browser behavior we cannot rely on `min-height`
- `<Layout height="parent" />` replaces `min-height: 100%` with `height:100%`
- Content to be rendered after a parent element should be placed as the last elements within it (since it allows overflow).
- Update `Search` and `Two Section` examples to follow the new convention
- This changes how `parent` works but makes the behavior consistent across browsers
- Limit page height on CI to work around SauceLabs different browser window sizes
- Includes @arahansen [fix for IE widths](https://github.com/obartra/reflex/pull/212/commits/969ccbb9d2629e9fef176f4c6dc0a66e37918d86)
Closes https://github.com/obartra/reflex/issues/216
Supersedes https://github.com/obartra/reflex/pull/212
BREAKING CHANGE

feat(browser): Add IE11 Support

---

src/dev.js
src/types.js
src/utils.js
storybook/index.js

Add boolean override parameter to `toggleOverlay()` and `toggleColor()` to force setting or unsetting (instead of toggling) a mode.
This behavior mimics jQuery or and DOM API's (e.g. `$().toggleClass` and `classList.toggle`) so it should be familiar for consumers.
Additionally, this is important for hot reloading where the setup code may runs multiple times and would otherwise keep toggling colors on and off
Closes https://github.com/obartra/reflex/issues/258

feat(dev): Allow override dev mode toggles

---

.babelrc
package.json
scripts/webpack.config.js
yarn.lock

This will allow users to specify their own version of react. And is more representative of requirements for realistic usage of reflex.
BREAKING CHANGE

build(peerDependencies): move react and prop-types to peerDependency

---

scripts/webpack.config.js
src/reflex.js

- webpack `external` wasn't properly pointing to the correct dependency
- export was improperly named
- added `GridProps` type to export as a helper for types
BREAKING CHANGE

fix(withGrid): match export name to file name

---

src/grid.js

currently Grid forces base to be 24. This should still be the default, but it should be overridable.
While this change is not breaking, this is being labelled as a breaking change since a previous commit, https://github.com/obartra/reflex/commit/cefbbe61c038e7ccadd36aa901ba0ba4c6cc5251 did not get tracked properly as breaking, and the major version was not bumped.
BREAKING CHANGE

feat(grid): allow modifying base prop

---

scripts/citests.sh

Test is currently failing on reflex/master. Disabling from CI since it's only
failing there and it's already part of the PR checks

ci(bithound): Remove bithound check

---

src/types.js

`size` and `offset` props can also accept strings. But flow currently sees this as an error.

fix(flow): allow valid number strings

---

renovate.json

Re-enables renovate but configures it to only run once a week. This is the minimum frequency we can set. If this still becomes too noisy I'll disable renovate altogether. Manual updates have been working well and with our current test coverage there's little manual work to do anyways.
Closes https://github.com/obartra/reflex/issues/269

ci(renovate): Re-enable renovate

---

renovate.json

No need to handle it in Renovate since CI already enforces it

ci(renovate): Disable lockfile maintanance

---

.flowconfig
index.js
package.json

- Remove `module` since although we can offer an ES6 build, it has additional (unlisted) dependencies: `cxs`, `preval`
- Default to a new `index.js` file that decides which file to serve based on `NODE_ENV` (similar to React's [approach](https://github.com/facebook/react/blob/master/packages/react/npm/index.js))
- Preserve the `browser` section from `package.json` but make it point to the minified build by default (this is useful for tools like unpkg, that will use it to load the minified version instead when importing https://unpkg.com/xn-reflex)

fix(npm): Correct npm targets

---

README.md

Moved codesandbox code to `https://github.com/obartra/reflex-playground`, updated reference in README
Closes https://github.com/obartra/reflex/issues/298

docs(readme): Update playground demo

---

.vscode/settings.json
README.md
package.json
scripts/flowgen.sh
src/flow.js
src/gymnast.tsx
src/log/index.spec.tsx
src/log/index.tsx
src/types.d.ts
src/utils/index.tsx
storybook/stories/grid/resolution.tsx
test/e2e/__snapshots__/gymnast.spec.tsx.snap
tsconfig.json
yarn.lock

Generates flow types based on typescript definitions.
- `flowgen` is on early development and fails for many files. Instead it's used only to convert the `types.d.ts` files.
- This simplifies the work but `src/flow.js` is generated and maintained manually
- Removes `utils` and `useResolution` exports since they were undocumented, unused externally and more work to type 😛 
- This is a first pass, as soon as a beta version is released we can start testing consumption

feat(flow): Generate flow types

---

package.json
src/col.tsx
src/grid.tsx
src/gymnast.tsx
src/types.d.ts
test/e2e/__snapshots__/gymnast.spec.tsx.snap

- Removes unused ref type
- Fixes (hopefully) TS types. TS types still seem to be broken when imported but they work when linking
Types works well when using `yarn link gymnast` on a separate project but not when installing the package. It's not that it can't find the package, the types are there but fail with `'onAuxClick' | 'onAuxClickCapture'` keys. Current attempt is to just remove them from the type for now
**next.11 update**: Local projects seem to be working as expected but codesandbox.io still fails to find the package (https://codesandbox.io/s/39kww200p)

remove unused ref

---

package.json
tsconfig.json

Export module bundle as ES5 by preventing babel and TS from overwriting each other (no need for TS to export anything other than definition files)

fix(build): transpile to ES5
